### ISSUE TITLE
요구사항 정리

### ISSUE THREAD

**Issue by jeongmoon417** [sarahyoon/myPlan#1]
필요한 기능

- [ ] 날짜 별로 해야 할 일을 여러개 등록한다
- [ ] 할 일 별로 완료 여부를 업데이트 할 수 있다.
- [ ] 해야할 일의 수 대비 완료한 일 계산 -> 일주일 단위, 한달 단위
- [ ] 프로젝트 단위의 해야할 일 등록?? --> 할 일이 카테고리가 있는것안가?

확장기능

- [ ] 임무 완수율에 따른 일간 정산
- [ ] 임무 완수율, 완수 패턴을 통한 미래 예측..

**Comment by sarahyoon** [comment]
+추가

- [ ] 목표설정하기

**Comment by jeongmoon417** [comment]
> +추가
> 
> * [ ]  목표설정하기
